source 'http://10.20.101.5/APP-IOS/OkdeerSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OKAdvertiseView' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
	pod 'Okdeer-CommonLibrary'  
  # Pods for OKAdvertiseView

end
